<?php
$data = $block->getTaskData();
?>
<form action="<?=$block->getLink('add')?>" method="post">
  <div class="form-group">
  	<div>
    <label for="name">Название:</label> <br />
    <input type="text" class="input" style="width: 300px" name="title" id="name" value="<?=$data['title']?>">
	</div>
	<div>
    <label for="text">Описание:</label> <br />
    <textarea class="input" name="text"  style="width: 300px" id="text"><?=$data['text']?></textarea>
	</div>
    <button type="submit" class="btn btn-default">Сохранить</button>
  </div>
  <input name="id" type="hidden" value="<?=$data['id']?>">
  <input name="form_key" type="hidden" value="<?=$block->getFormKey()?>">
</form>
<br /><br />
<a href="<?=$block->getLink('tasks')?>">Вернуться к списку задач</a>
